function nivelGraficos(f,a,b,c,d)

% ESTE m.FILE CRIA 2 REPRESENTAÇÕES GRÁFICAS PARA FUNÇÕES f DE 2 VARIÁVEIS
% x E y. CONCRETAMENTE OS SEUS OUTPUTS SÃO:
% - GRÁFICO (TRIDIMENSIONAL) DA FUNÇÃO f NUM INTERVALO INDICADO [a,b]*[c,d]
% - REPRESENTAÇÃO DAS CURVAS DE NÍVEL DA FUNÇÃO f NO MESMO INTERVALO
% - REPRESENTAÇÃO GRÁFICA DO SIMÉTRICO DO VETOR GRADIENTE DE f SOBRE AS
%   CURVAS DE NÍVEL DE f

% NENHUM DESTES INPUTS f, a, b, c, d É AQUI EXPLICITADO, VISTO QUE A
% VANTAGEM DESTE m.FILE É SERVIR DE SUPORTE GENÉRICO NA EXECUÇÃO DE OUTROS
% m.FILES; SÃO ESTES ÚLTIMOS QUE VÃO "PEDIR" EXPLICITAÇÃO DOS INPUTS f, a,
% b, c E d (OU JÁ OS TÊM DEFINIDOS COM ESTAS MESMAS DESIGNAÇÕES/LETRAS).

% QUANDO NECESSÁRIOS, OS ELEMENTOS f, a, b, c, d VÃO SER DADOS COMO INPUTS
% DA SEGUINTE FORMA:
% - A FUNÇÃO f É DEFINIDA COMO FUNCTION-HANDLE f=@(x) [O QUE PERMITE UMA
%   ESCRITA MAIS SIMPLES E O SEU USO INDIRETO NOUTRAS FUNÇÕES] ATRAVÉS DE
%   UMA EXPRESSÃO NAS 2 VARIÁVEIS x(1) E x(2) [RESPETIVAMENTE x E y],
%   VARIÁVEIS ESTAS QUE COMPOÊM A VARIÁVEL x DA FUNÇÃO f; A VARIÁVEL x DE f
%   É TRATADA A NÍVEL DO MATLAB COMO UMA MATRIZ [x(1),x(2)]
% - O INTERVALO [a,b]*[c,d]


% PARTE 1: SCHEDULE DO INTERVALO I=[a,b]x[c,d] ONDE VARIAM x E y

h=5e-2;       % INCREMENTO h=5x10^(-2) QUE DETERMINA O Nº DE DIVISÕES EM I 
x=a:h:b;      % PARTIÇÃO DA VARIÁVEL x: DE a ATÉ b COM O INCREMENTO h
y=c:h:d;      % PARTIÇÃO DA VARIÁVEL y: DE c ATÉ d COM O MESMO INCREMENTO h


% PARTE 2: CRIAÇÃO DE GRELHA NO EIXO DOS XX (X-EIXO) E EIXO DOS YY (Y-EIXO)

[X,Y]=meshgrid(x,y);   % COMANDO meshgrid E IDENTIFIC. DE X COM x E Y COM y


% PARTE 3: DEFINIÇÃO DO Z-EIXO COMO O DE REPRESENTAÇÃO DOS VALORES DE f 

for i=1:length(y)            % INDEXAÇÃO por i DOS VALORES DE y, ATÉ AO SEU 
                             % Nº MÁXIMO length(y)
    for j=1:length(x)        % DADA A INDEXAÇÃO ANTERIOR, SEGUE A INDEXAÇÃO 
                             % POR j DOS VALORES DE x, ATÉ length(x)
        v=[X(i,j),Y(i,j)];   % CONSTRUÇÃO (COMO MATRIZ) DO VETOR v DE COOR-
                             % DENADAS x E y
        Z(i,j)=f(v);         % Z-EIXO ONDE SÃO REPRESENTADAS AS IMAGENS POR 
                             % f DOS VETORES v (MATRIZES)
    end
end


% PARTE 4: DEFINIÇÃO DO VETOR GRADIENTE COMO MATRIZ [d1,d2]

[d1,d2]=gradient(Z, h);  % COMANDO gradient PARA CÁLCULO DO GRADIENTE NUMÉ-
                         % RICO, ONDE d1 E d2 SÃO, RESPETIVAMENTE, AS DERI-
                         % VADAS PARCIAIS EM ORDEM A x E A y, E É INDICADO
                         % O MESMO INCREMENTO h PARA Z=f(x,y)=f(v)


% PARTE 5: OUTPUT "GRÁFICO TRIDIMENSIONAL DA FUNÇÃO f"

meshc(X,Y,Z)        % COMANDO meshc PARA OBTER O GRÁFICO DE f     

figure              % COMANDO figure A INDICAR A EXIBIÇÃO DO GRÁFICO DE f


% PARTE 6: OUTPUT "CURVAS DE NÍVEL DA FUNÇÃO f"
 
contour(X,Y,Z,'ShowText','on') % COMANDO contour PARA CURVAS DE NÍVEL, ONDE
                               % 'ShowText' INDICA QUE Z É INTERPRETADO CO-
                               % MO ALTURAS EM RELAÇÃO AO XY-PLANO E 'on' 
                               % TRANSFORMA A INFORMAÇÃO MATRICIAL DOS VE-
                               % TORES v EM LISTAS

hold on     % COMANDO hold on PARA QUE ESTE OUTPUT E O SEGUINTE SEJAM DADOS
            % NA MESMA FIGURA, OU SEJA, RETEM ESTE OUTPUT, QUE NÃO É ENTÃO 
            % SUBSTITUIDO PELO PRÓXIMO OUTPUT
           

% PARTE 7: OUTPUT "REPRESENTAÇÃO GRÁFICA DO SIMÉTRICO DO GRADIENTE"

quiver(X,Y,-d1,-d2) % COMANDO quiver PARA DESENHAR NO SISTEMA DE EIXOS XOY,
                    % COMO SETAS, O CAMPO DE VETORES SIMÉTRICO DO GRADIENTE 
                    % E ONDE -d1 E -d2 SÃO AS COORDENADAS A REPRESENTAR

% NÃO É NECESSÁR. O COMANDO hold off PQ A hold on APENAS SE SEGUIU 1 OUTPUT

% NO FINAL DEVEMOS CORRER O m.FILE PARA VERIFICAR SE PEDE OS INPUTS
% PRETENDIDOS



